name: vsnp_determine_ref_from_data
owner: greg
description: |
  Contains a tool that sniffs bacterial genome samples to discover the primary species within the sample.
homepage_url: https://github.com/USDA-VS/vSNP
long_description: |
  Contains a tool that sniffs bacterial genome samples to discover the primary species within the sample.
remote_repository_url: https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/sequence_analysis/vsnp/vsnp_determine_ref_from_data
type: unrestricted
categories:
  - Sequence Analysis
