name: queue_genotype_workflow
owner: greg
description: |
  Contains a tool that uses the Galaxy API to execute the complete multilocus genotype pipeline for corals or symbiants.
homepage_url: http://baumslab.org
long_description: |
  Contains a tool that uses the Galaxy API to execute the complete multilocus genotype pipeline for corals or symbiants.
remote_repository_url: https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/corals/queue_genotype_workflow
type: unrestricted
categories:
  - Micro-array Analysis
