name: vsnp_build_tables
owner: greg
description: |
  Contains a tool that produces Excel spreadsheets from outputs produced by the vsnp_get_snps tool.
homepage_url: https://github.com/USDA-VS/vSNP
long_description: |
  Contains a tool that produces Excel spreadsheets from outputs produced by the vsnp_get_snps tool.
remote_repository_url: https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/sequence_analysis/vsnp/vsnp_build_tables
type: unrestricted
categories:
  - Sequence Analysis
